services:
  mygo:
    build:
      context: .
      dockerfile: Dockerfile
    image: mygo
    container_name: mygo
    volumes:
      - $HOME/mygo-anime:/root/mygo-anime
      - .env:/app/.env
    network_mode: host
    environment:
      - GIN_MODE=release
    restart: always
