services:
  mygo:
    build:
      context: .
      dockerfile: Dockerfile
    image: mygo
    container_name: mygo
    volumes:
      - /mnt/d/ocr-videos:/mnt/d/ocr-videos
      - .env:/app/.env
      - ./internal/config/config.yaml:/app/internal/config/config.yaml
    network_mode: host
    environment:
      - GIN_MODE=release
      - CONFIG_PATH=/app/internal/config/config.yaml
    restart: always
